name: 🎁 Feature Request
description: Suggest a feature or improvement
title: "🎁 "
labels: [":bulb: feature request"]
assignees:
  - billsioros
body:
  - type: textarea
    id: change-description
    attributes:
      label: What would you like to be implemented?
      description: Describe what you would like to see implemented!
      placeholder: Please provide a concise description of the feature you want implemented, as well as the reasoning behind it.
    validations:
      required: true
  - type: checkboxes
    id: duplicate-issue
    attributes:
      label: Is this a duplicate issue?
      description: By submitting this issue, you confirm that you have made sure that this is not a duplicate issue
      options:
        - label: I confirm that this is not a duplicate issue
          required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://the-dotify-project.github.io/dotify/latest/CODE_OF_CONDUCT/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
